# Generated by Django 3.2.7 on 2021-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(choices=[('Seattle', 'Seattle'), ('New York', 'New York'), ('Philadelphia', 'Philadelphia'), ('Boston', 'Boston'), ('Chicago', 'Chicago'), ('Los Angeles', 'Los Angeles'), ('San Diego', 'San Diego'), ('Dallas', 'Dallas'), ('Houston', 'Houston'), ('Atlanta', 'Atlanta'), ('Miami', 'Miami')], default=('Seattle', 'Seattle'), max_length=100, verbose_name='City Name')),
                ('course_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Title')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='Course Image')),
            ],
        ),
    ]
