# Generated by Django 3.2.7 on 2021-09-21 11:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210921_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Facebook_group_called',
            field=models.URLField(blank=True, null=True, verbose_name='Join Facebook group called Blockchain in Seattle'),
        ),
        migrations.AddField(
            model_name='course',
            name='LinkedIn_group_called',
            field=models.URLField(blank=True, null=True, verbose_name='Join LinkedIn group called Blockchain in Seattle'),
        ),
        migrations.AddField(
            model_name='course',
            name='Meetup_called',
            field=models.URLField(blank=True, null=True, verbose_name='Join Meetup called Blockchain Meetup in Seattle'),
        ),
        migrations.AddField(
            model_name='course',
            name='companies_linkedIn',
            field=models.URLField(blank=True, null=True, verbose_name='Blockchain Companies in Seattle on LinkedIn'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_eligibility',
            field=models.TextField(blank=True, null=True, verbose_name='Who can take the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Course Ending Date'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_outline',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Course Outline'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Course Starting Date'),
        ),
        migrations.AddField(
            model_name='course',
            name='jobs',
            field=models.URLField(blank=True, null=True, verbose_name='Blockchain Jobs in Seattle'),
        ),
        migrations.AddField(
            model_name='course',
            name='professionals_linkedIn',
            field=models.URLField(blank=True, null=True, verbose_name='Blockchain Professionals in Seattle on LinkedIn'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
