# Generated by Django 3.2.7 on 2021-09-22 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210921_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(choices=[('Seattle', 'Seattle'), ('New York', 'New York'), ('Philadelphia', 'Philadelphia'), ('Boston', 'Boston'), ('Chicago', 'Chicago'), ('Los Angeles', 'Los Angeles'), ('San Diego', 'San Diego'), ('Dallas', 'Dallas'), ('Houston', 'Houston'), ('Atlanta', 'Atlanta'), ('Miami', 'Miami')], default=('Seattle', 'Seattle'), max_length=100, verbose_name='City Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='city_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.city', verbose_name='Course City Name'),
        ),
    ]
