# Generated by Django 3.2.7 on 2021-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210922_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(choices=[('Seattle', 'Seattle'), ('New York', 'New York'), ('Philadelphia', 'Philadelphia'), ('Boston', 'Boston'), ('Chicago', 'Chicago'), ('Los Angeles', 'Los Angeles'), ('San Diego', 'San Diego'), ('Dallas', 'Dallas'), ('Houston', 'Houston'), ('Atlanta', 'Atlanta'), ('Miami', 'Miami'), ('Surat', 'Surat'), ('Valsad', 'Valsad')], default=('Seattle', 'Seattle'), max_length=100, verbose_name='City Name'),
        ),
    ]
