# Generated by Django 3.2.7 on 2021-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(choices=[('Seattle', 'Seattle'), ('New York', 'New York'), ('Philadelphia', 'Philadelphia'), ('Boston', 'Boston'), ('Chicago', 'Chicago'), ('Los Angeles', 'Los Angeles'), ('San Diego', 'San Diego'), ('Dallas', 'Dallas'), ('Houston', 'Houston'), ('Atlanta', 'Atlanta'), ('Miami', 'Miami'), ('Surat', 'Surat'), ('Valsad', 'Valsad'), ('Kolkata', 'Kolkata'), ('Ahmedabad', 'Ahmedabad')], default=('Seattle', 'Seattle'), max_length=100, verbose_name='City Name'),
        ),
    ]
