# Generated by Django 3.2.7 on 2021-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='City Name'),
        ),
    ]
