# Generated by Django 3.2.7 on 2021-09-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_city_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(choices=[('IN', 'IN'), ('US', 'US')], default=('IN', 'IN'), max_length=500, verbose_name='Choose Your Country')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Course Starting Date')),
                ('ending_date', models.DateField(blank=True, null=True, verbose_name='Course Ending Date')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
