# Generated by Django 3.2.7 on 2021-09-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210924_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cont_status',
            field=models.BooleanField(default=False),
        ),
    ]
