# Generated by Django 3.2.7 on 2021-09-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_country_cont_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_start_date', models.DateField(blank=True, null=True, verbose_name='Batch Starting Date')),
                ('batch_end_date', models.DateField(blank=True, null=True, verbose_name='Batch Ending Date')),
                ('batch_status', models.BooleanField(default=False)),
                ('batch_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.city', verbose_name='Batch For City')),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_city',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_start_date',
        ),
    ]
