# Generated by Django 3.2.7 on 2021-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20210927_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.city', unique=True, verbose_name='Course City'),
        ),
    ]
